### ISSUE TITLE
脚本是否安全

### ISSUE THREAD

**Issue by skynet2791** [idhyt/CentOS-DXF#2]
运行过一次降级脚本和服务器架设脚本，然后挖了一夜的矿……

**Comment by idhyt** [comment]
你一定是在逗我。。。

ps. 脚本代码开源的。

**Comment by skynet2791** [comment]
> 你一定是在逗我。。。
> 
> ps. 脚本代码开源的。

当时没细看，后来翻了翻，应该没有问题。
